ALTER TABLE BOARD
ADD COLUMN DUE_DATE_CF VARCHAR(255);

ALTER TABLE BOARD
ADD COLUMN DUE_DATE_TYPE VARCHAR(255);

UPDATE BOARD SET
DUE_DATE_CF = 'duedate',
DUE_DATE_TYPE = 'FIRST_AND_LAST_DUE_DATE'
WHERE CALC_DUE_DATE = TRUE;

ALTER TABLE BOARD
DROP COLUMN CALC_DUE_DATE;