ALTER TABLE user_config
  ADD COLUMN LEAD_TIME_CHART_TYPE VARCHAR(255);

ALTER TABLE user_config
  ADD COLUMN THROUGHPUT_CHART_TYPE VARCHAR(255);

UPDATE user_config SET LEAD_TIME_CHART_TYPE = 'DOUGHNUT';
UPDATE user_config SET THROUGHPUT_CHART_TYPE = 'DOUGHNUT';