ALTER TABLE BOARD
    ADD COLUMN USE_LAST_OCCURRENCE_WHEN_CALCULATE_LEAD_TIME BOOLEAN;

UPDATE BOARD
SET USE_LAST_OCCURRENCE_WHEN_CALCULATE_LEAD_TIME = FALSE
    WHERE USE_LAST_OCCURRENCE_WHEN_CALCULATE_LEAD_TIME IS NULL;

ALTER TABLE BOARD
ALTER COLUMN USE_LAST_OCCURRENCE_WHEN_CALCULATE_LEAD_TIME SET NOT NULL;

